import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

test('公式地図の編集・override・保存読込・パンズーム・検証・障害物', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?tool=editor');
  await expect(page.getByText('京都市公式KML · 227国勢統計区')).toBeVisible();
  await expect(page.locator('.calculating')).toHaveCount(0);
  await expect(page.locator('path[data-region-id]')).toHaveCount(227);
  await expect(page.getByText('採用 0 / 227', { exact: true })).toBeVisible();
  await page.getByLabel('行政区フィルター').selectOption('26101');
  await page.getByRole('button', { name: '区を全採用', exact: true }).click();
  await expect(page.getByText('採用 19 / 227', { exact: true })).toBeVisible();
  await expect(page.locator('.calculating')).toHaveCount(0);
  await page.getByLabel('地域を検索').fill('待鳳');
  await page.locator('.region-list button').first().click();
  await expect(page.getByRole('heading', { name: '待鳳', exact: true })).toBeVisible();
  await page.getByLabel('補給拠点', { exact: true }).check();
  await page.getByText('互換用 / 将来検討（homeWardId）', { exact: true }).click();
  await page.getByLabel('ホーム勢力', { exact: true }).selectOption('26102');
  await page.getByLabel('初期ユニット', { exact: true }).check();
  await page.getByLabel('初期ユニットの勢力', { exact: true }).selectOption('26102');
  await expect(page.locator('.calculating')).toHaveCount(0);
  await expect(page.locator('.supply-marker')).toHaveCount(1);
  await expect(page.locator('.unit-marker')).toHaveCount(1);
  const deleteNeighbor = page.getByRole('button', { name: /への隣接を削除/ }).first();
  await deleteNeighbor.click();
  await expect(page.locator('.calculating')).toHaveCount(0);
  await page.getByText('手動override (1)', { exact: true }).click();
  await expect(page.getByRole('button', { name: '差分を取消' })).toHaveCount(1);
  await page.getByRole('button', { name: '差分を取消' }).click();
  await expect(page.locator('.calculating')).toHaveCount(0);
  // Add a non-geographic edge via the editor and ensure it is saved as a diff.
  await page.getByRole('button', { name: '隣接override', exact: true }).click();
  await page.getByLabel('地域を検索').fill('雲ヶ畑');
  await page.locator('.region-list button').first().click();
  await expect(page.locator('.calculating')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '待鳳', exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '設定JSONを保存', exact: true }).click();
  const downloaded = await downloadPromise;
  const saved = JSON.parse(await readFile((await downloaded.path())!, 'utf8'));
  expect(saved.adjacencyAdd).toEqual([['kyoto-26101-01', 'kyoto-26101-19']]);
  expect(saved.regions['kyoto-26101-01']).toMatchObject({ isSupplyCenter: true, homeWardId: '26102', startingUnit: { ownerWardId: '26102' } });
  await page.getByLabel('この地域を採用').uncheck();
  await page.getByRole('button', { name: /^検証/ }).click();
  await expect(page.getByText(/除外地域に初期配置があります/)).toBeVisible();
  await expect(page.getByRole('button', { name: 'MapDefinition出力', exact: true })).toBeDisabled();
  await page.getByLabel('設定JSONを読込', { exact: true }).setInputFiles({ name: 'saved.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(saved)) });
  await expect(page.locator('.calculating')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'MapDefinition出力', exact: true })).toBeEnabled();
  const before = await page.locator('svg.map').getAttribute('viewBox');
  await page.getByRole('button', { name: '拡大', exact: true }).click();
  expect(await page.locator('svg.map').getAttribute('viewBox')).not.toBe(before);
  await page.getByRole('button', { name: '全体に戻す', exact: true }).click();
  const bounds = (await page.locator('svg.map').boundingBox())!;
  await page.mouse.move(bounds.x + 20, bounds.y + 20); await page.mouse.down();
  await page.mouse.move(bounds.x + 70, bounds.y + 50, { steps: 5 }); await page.mouse.up();
  expect(await page.locator('svg.map').getAttribute('viewBox')).not.toBe(before);
  await page.getByRole('button', { name: '全体に戻す', exact: true }).click();
  await page.screenshot({ path: 'test-results/kyoto-editor.png', fullPage: true });
  await page.reload();
  await expect(page.getByText('採用 19 / 227', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '架空サンプルで確認', exact: true }).click();
  await expect(page.getByText('架空サンプル（京都の地図ではありません）', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '分断テスト用の障害物を追加', exact: true }).click();
  await expect(page.locator('.obstacle')).toHaveCount(1);
  await page.getByRole('button', { name: /^検証/ }).click();
  await expect(page.getByText(/障害物差し引き後は2部分です/).first()).toBeVisible();
  await page.screenshot({ path: 'test-results/sample-obstacle.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('変換データ未配置はサンプル表示、壊れた設定は現設定を保持', async ({ page }) => {
  await page.route('**/regions.json', route => route.fulfill({ status: 404, body: '' }));
  await page.goto('/?tool=editor');
  await expect(page.getByText('架空サンプル（京都の地図ではありません）', { exact: true })).toBeVisible();
  await page.getByLabel('設定JSONを読込').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{ invalid') });
  await expect(page.getByText(/読込エラー:/)).toBeVisible();
  await expect(page.getByText('採用 4 / 4', { exact: true })).toBeVisible();
  await page.getByLabel('障害物GeoJSONを読込').setInputFiles(resolve('data/maps/sample-obstacle.geojson'));
  await expect(page.locator('.obstacle')).toHaveCount(1);
  await page.locator('path[data-region-id="sample-b"]').hover();
  await expect(page.locator('.map-footer')).toContainText('架空地域B');
  await page.locator('path[data-region-id="sample-b"]').click();
  await expect(page.getByRole('heading', { name: '架空地域B', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '採用・除外を切替', exact: true }).click();
  await page.locator('path[data-region-id="sample-b"]').click();
  await expect(page.getByLabel('この地域を採用')).not.toBeChecked();
  const beforeWheel = await page.locator('svg.map').getAttribute('viewBox');
  await page.locator('svg.map').hover(); await page.mouse.wheel(0, -150);
  await expect(page.locator('svg.map')).not.toHaveAttribute('viewBox', beforeWheel!);
});

test('地図JSONが破損していてもエラーを表示し、サンプルに切り替えられる', async ({ page }) => {
  await page.route('**/regions.json', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' }));
  await page.goto('/?tool=editor');
  await expect(page.getByRole('alert')).toContainText('地図を読み込めません');
  await page.getByRole('button', { name: '架空サンプルを開く', exact: true }).click();
  await expect(page.getByText('採用 4 / 4', { exact: true })).toBeVisible();
});
