import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createConfig,configSchema,datasetSchema,type MapConfig} from '../../packages/shared/model';
import {completeKyotoTestScenario} from '../scenario-fixture';
import type {PublicRoomView,PrivatePlayerView} from '../../packages/shared/online';
import {legalOrders} from '../../packages/rules-core';
async function start(pages:Page[],config:MapConfig,wards:string[]){
 for(let i=0;i<pages.length;i++){await pages[i].goto('/');await pages[i].getByRole('button',{name:'オンライン対戦',exact:true}).click();await pages[i].getByLabel('オンラインニックネーム').fill(`5C-${i}`);await pages[i].getByLabel('オンライン希望区').selectOption(wards[i]);await expect(pages[i].getByText('サーバー接続中',{exact:true})).toBeVisible();}
 await pages[0].getByRole('button',{name:'ルームを作成',exact:true}).click();const code=await pages[0].getByTestId('room-code').innerText();
 await pages[0].getByLabel('京都シナリオJSONを読み込む').setInputFiles({name:'phase5c-test-only.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(config))});
 for(const page of pages.slice(1)){await page.getByLabel('参加ルームコード').fill(code);await page.getByRole('button',{name:'ルームへ参加',exact:true}).click();}
 await pages[0].getByRole('button',{name:'オンラインゲーム開始',exact:true}).click();for(const page of pages){await expect(page.getByTestId('online-phase')).toContainText('第1年 · 春');await page.getByRole('button',{name:'イベント・結果',exact:true}).click();}
}
async function finalize(pages:Page[]){for(const page of pages)await page.getByRole('button',{name:'命令書を確定',exact:true}).click();}
function watch(page:Page){const state:{room?:PublicRoomView;self?:PrivatePlayerView}={};page.on('websocket',socket=>socket.on('framereceived',f=>{const payload=String(f.payload);if(!payload.startsWith('42['))return;const [event,value]=JSON.parse(payload.slice(2));if(event==='publicState')state.room={...value,map:value.map??state.room?.map};if(event==='privateState')state.self=value;}));return state;}

test('実京都190/72/59・3人の1920/1280画面・命令反応・支援・開いた結果のまま次命令・UI状態とサーバー状態',async({browser})=>{
 test.setTimeout(90000);const contexts=await Promise.all([0,1,2].map(()=>browser.newContext({viewport:{width:1920,height:1080}}))),pages=await Promise.all(contexts.map(c=>c.newPage()));const state=watch(pages[0]);const errors:string[]=[];pages.forEach(p=>p.on('pageerror',e=>errors.push(e.message)));
 try{
  const config=configSchema.parse(JSON.parse(await readFile('tests/fixtures/phase5a1-kyoto-map-config.json','utf8')));await start(pages,config,['26102','26104','26111']);const page=pages[0];await expect(page.locator('.supply-circle')).toHaveCount(72);
  await page.screenshot({animations:'disabled',path:'test-results/phase5c-main-1920.png'});await page.setViewportSize({width:1280,height:720});await page.screenshot({animations:'disabled',path:'test-results/phase5c-main-1280.png'});
  const map=state.room!.map!,units=state.room!.game!.board.units,own=units.filter(u=>u.ownerWardId==='26102');const support=own.flatMap(u=>legalOrders(map,units,u.unitId)).find(o=>o.type==='support-move'&&own.some(u=>u.unitId===o.targetUnitId));if(!support||support.type!=='support-move')throw Error('support fixture');const supporter=units.find(u=>u.unitId===support.unitId)!,target=units.find(u=>u.unitId===support.targetUnitId)!;
  await page.getByLabel('オンライン行政区').selectOption('26102');await page.getByRole('button',{name:/選択(?:区|地域)を拡大/}).click();await page.locator(`[data-marker-region="${target.regionId}"]`).press('Enter');await expect(page.getByLabel('選択軍の操作')).toBeVisible();await page.screenshot({animations:'disabled',path:'test-results/phase5c-command-dock.png'});
  await page.locator(`[data-region-id="${support.destination}"]`).dispatchEvent('contextmenu',{button:2});await expect(page.locator('.move-line')).toHaveCount(1);await expect(page.locator('.order-accepted-pulse')).toHaveCount(1);
  await page.getByRole('button',{name:'命令を変更',exact:true}).click();await expect(page.locator('.move-line')).toHaveCount(0);await expect(page.locator('.order-accepted-pulse')).toHaveCount(0);await page.getByRole('button',{name:'待機',exact:true}).click();await expect(page.locator('.hold-indicator')).toHaveCount(1);
  await page.locator(`[data-marker-region="${supporter.regionId}"]`).press('Enter');await page.getByRole('button',{name:'支援',exact:true}).click();await page.locator(`[data-marker-region="${target.regionId}"]`).press('Enter');await page.screenshot({animations:'disabled',path:'test-results/phase5c-support-wizard.png'});await page.getByRole('button',{name:'この軍の現在地を守る',exact:true}).click();await expect(page.locator('.support-line')).toHaveCount(1);
  const event=page.getByTestId('current-events').locator('.event-card').first();await event.getByRole('button',{name:'地図で見る',exact:true}).click();await expect(page.locator('.event-pulse')).not.toHaveCount(0);await page.screenshot({animations:'disabled',path:'test-results/phase5c-event-focus.png'});
  const neutral=map.regions.find(r=>r.isSupplyCenter&&state.room!.game!.board.regionControl[r.regionId]?.supplyCenterOwnerWardId===null)!;await page.locator(`[data-supply-region="${neutral.regionId}"]`).dispatchEvent('mouseover');await expect(page.getByRole('tooltip')).toContainText('中立（未所有）');await page.screenshot({animations:'disabled',path:'test-results/phase5c-neutral-sc.png'});
  await finalize(pages);await page.bringToFront();await expect(page.getByLabel('裁定演出')).toHaveAttribute('data-presentation-stage','summary',{timeout:8000});await expect(page.locator('.sc-gain')).toContainText('補給拠点');await expect(page.locator('.sc-captured')).not.toHaveCount(0);await expect(page.getByTestId('previous-result-drawer')).toBeVisible();await expect(page.getByRole('button',{name:'命令書を確定',exact:true})).toBeEnabled();await expect(page.locator('.presentation-layer')).toHaveCount(0);await expect(page.locator('html')).toHaveAttribute('data-bgm-context','domestic');
  const next=state.room!.game!.board.units.find(u=>u.ownerWardId==='26102')!;await page.locator(`[data-marker-region="${next.regionId}"]`).press('Enter');await page.getByRole('button',{name:'待機',exact:true}).click();await expect.poll(()=>state.self?.orders.some(o=>o.unitId===next.unitId&&o.type==='hold')).toBe(true);await expect(page.getByTestId('previous-result-drawer')).toBeVisible();expect((await page.locator('svg.map').boundingBox())!.height).toBeGreaterThan(200);await page.screenshot({animations:'disabled',path:'test-results/phase5c-drawer-next-command.png'});
  const phase=state.room!.game!.phaseKey;await page.getByRole('button',{name:'結果を閉じる',exact:true}).click();await page.getByRole('button',{name:'前回の行軍結果',exact:true}).click();expect(state.room!.game!.phaseKey).toBe(phase);await expect(page.getByRole('button',{name:'命令書を確定',exact:true})).toBeEnabled();await page.getByRole('button',{name:'イベント・結果',exact:true}).click();await expect(page.getByTestId('previous-result-drawer')).toHaveCount(0);await page.getByRole('button',{name:'前回の行軍結果',exact:true}).click();await expect(page.getByTestId('previous-result-drawer')).toBeVisible();expect(state.room!.game!.phaseKey).toBe(phase);
  await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.selected-army .unit-marker')).toHaveCSS('animation-name','none');expect(errors).toEqual([]);
 }finally{await Promise.all(contexts.map(c=>c.close()));}
});

test('撤退必須と開いた前回結果を併存し、閉じずに撤退・秋命令・冬Build/Disbandを入力',async({browser})=>{
 test.setTimeout(90000);const dataset=datasetSchema.parse(JSON.parse(await readFile('data/generated/regions.json','utf8'))),config=createConfig(dataset),wards=['26101','26102','26103'];const groups=wards.map(w=>dataset.regions.filter(r=>r.wardId===w).slice(0,2));
 for(let i=0;i<3;i++)for(let j=0;j<2;j++)config.regions[groups[i][j].regionId]={enabled:true,isSupplyCenter:j===0||i===0,homeWardId:j===0||i===0?groups[i][j].wardId:null,startingUnit:j===0||i===0?{ownerWardId:groups[i][j].wardId,type:'army'}:null};
 config.adjacencyAdd=[[groups[0][0].regionId,groups[1][0].regionId],[groups[0][1].regionId,groups[1][0].regionId],[groups[1][0].regionId,groups[1][1].regionId]];completeKyotoTestScenario(dataset,config);
 const contexts=await Promise.all(wards.map(()=>browser.newContext({viewport:{width:1280,height:720}}))),pages=await Promise.all(contexts.map(c=>c.newPage()));try{
  await start(pages,config,wards);const attack=pages[0],defend=pages[1];await attack.locator(`[data-marker-region="${groups[0][0].regionId}"]`).press('Enter');await attack.locator(`[data-region-id="${groups[1][0].regionId}"]`).dispatchEvent('contextmenu',{button:2});await expect(attack.locator('.move-line')).toHaveCount(1);
  await attack.locator(`[data-marker-region="${groups[0][1].regionId}"]`).press('Enter');await attack.getByRole('button',{name:'支援',exact:true}).click();await attack.locator(`[data-marker-region="${groups[0][0].regionId}"]`).press('Enter');await attack.getByRole('button',{name:/現在の移動命令:/}).click();await finalize(pages);
  await expect(defend.getByTestId('online-phase')).toContainText('春 · 撤退');await expect(defend.getByText('撤退が必要です · 撤退中は交渉禁止',{exact:true})).toBeVisible();await expect(defend.getByLabel('オンライン秘密撤退先')).toBeDisabled();await expect(defend.getByTestId('previous-result-drawer')).toBeVisible();await expect(defend.getByLabel('オンライン秘密撤退先')).toBeEnabled();await expect(defend.locator('.retreat-required-marker')).toHaveCount(1);expect((await defend.locator('svg.map').boundingBox())!.height).toBeGreaterThan(180);await defend.screenshot({animations:'disabled',path:'test-results/phase5c-retreat-drawer.png'});
  await defend.getByLabel('オンライン秘密撤退先').selectOption(groups[1][1].regionId);await defend.getByRole('button',{name:'撤退命令書を確定',exact:true}).click();for(const p of pages){await expect(p.getByTestId('online-phase')).toContainText('秋 · 移動命令');await expect(p.getByRole('button',{name:'命令書を確定',exact:true})).toBeEnabled();}
  await finalize(pages);await attack.bringToFront();await expect(attack.getByTestId('previous-result-drawer')).toBeVisible();await expect(attack.getByRole('button',{name:'冬調整を確定',exact:true})).toBeEnabled({timeout:10000});await attack.getByLabel(`オンラインBuild ${groups[0][0].name}`,{exact:true}).check();await attack.getByRole('button',{name:'冬調整を確定',exact:true}).click();await defend.getByLabel(`オンラインDisband ${groups[1][1].name}`,{exact:true}).check();await defend.getByRole('button',{name:'冬調整を確定',exact:true}).click();await expect(attack.locator('.army-built')).toHaveCount(1);await expect(defend.locator('.army-disbanded')).toHaveCount(1);await expect(attack.getByRole('heading',{name:'勝利',exact:true})).toBeVisible();await expect(defend.getByRole('heading',{name:/第\d位/})).toBeVisible();await attack.getByLabel('ゲーム終了結果').screenshot({animations:'disabled',path:'test-results/phase5c-winner.png'});await defend.getByLabel('ゲーム終了結果').screenshot({animations:'disabled',path:'test-results/phase5c-nonwinner.png'});await expect(attack.getByRole('heading',{name:'GAME OVER',exact:true})).toHaveCount(0);
 }finally{await Promise.all(contexts.map(c=>c.close()));}
});
