import { z } from 'zod';
import { wardSchema } from './model';
import { eventSettingsSchema, eventRecordSchema, gameOrderSchema } from './events';

export const victorySettingsSchema=z.object({baseVictoryTargetSC:z.number().int().positive(),referencePlayerCount:z.number().int().positive(),missingPlayerSCBonus:z.number().int().nonnegative(),maxYears:z.number().int().positive(),requiredRivalInitialSupplyCentersForInstantWin:z.number().int().nonnegative().default(2)}).strict();
const count=z.number().int().nonnegative();
export const standingSchema=z.object({wardId:wardSchema,rank:z.number().int().positive(),supplyCenters:count,controlledRegions:count,units:count}).strict();
export const endResultSchema=z.object({reason:z.enum(['supply-target','elimination-final-year','max-years']),year:z.number().int().positive(),season:z.enum(['spring','autumn','winter']),winners:z.array(wardSchema),standings:z.array(standingSchema),eliminated:z.array(z.object({wardId:wardSchema,reasons:z.array(z.enum(['zero-sc','zero-non-sc']))}).strict())}).strict();
export type EndResult=z.infer<typeof endResultSchema>;
export const metricsSchema=z.object({averageOrdersSeconds:z.number().nonnegative(),ordersPhases:count,standoffs:count,dislodgements:count,eventCounts:z.object({bicycle:count,barricade:count,roadwork:count,bus:count}).strict(),bicyclePickups:count,bicycleUses:count,barricadePickups:count,barricadeUses:count,barricadeDeployments:count,supportHoldCount:count.default(0),supportMoveCount:count.default(0),adjudicationPresentationSkipped:count.default(0),rivalInitialSCByWard:z.record(z.string(),count).default({}),neutralSCOwnedByWard:z.record(z.string(),count).default({})}).strict();
export type MatchSummary=z.infer<typeof metricsSchema>;
const statsSchema=standingSchema.omit({rank:true}).extend({inventory:z.object({bicycle:count,barricade:count}).strict(),rivalInitialSC:count.default(0),neutralSCOwned:count.default(0)}).strict();
export const logRecordSchema=z.object({type:z.enum(['game-start','phase-start','player-finalized','all-finalized','adjudication','retreat','sc-update','event-generation','equipment-pickup','barricade-deployment','barricade-expiration','winter-adjustment','elimination','game-end','presentation-skipped']),timestamp:z.string().datetime(),year:z.number().int().positive(),season:z.enum(['spring','autumn','winter']),phase:z.enum(['orders','retreats','sc-update','adjustments','end-of-year','finished']),playerId:z.string().optional(),elapsedSeconds:z.number().nonnegative().optional(),submittedOrderCount:count.optional(),resolvedOrders:z.array(gameOrderSchema).optional(),events:z.array(eventRecordSchema).optional(),equipment:z.object({type:z.enum(['bicycle','barricade']),regionId:z.string(),ownerWardId:wardSchema}).strict().optional(),edge:z.object({a:z.string(),b:z.string()}).strict().optional(),standoffCount:count.optional(),dislodgementCount:count.optional(),buildCount:count.optional(),disbandCount:count.optional(),stats:z.array(statsSchema),end:endResultSchema.optional()}).strict();
export const matchLogSchema=z.object({version:z.literal(1),gameId:z.string(),scenarioHash:z.string(),playerCount:z.number().int().positive(),wardAssignment:z.record(z.string(),wardSchema),players:z.array(z.object({playerId:z.string(),nickname:z.string(),wardId:wardSchema}).strict()),inactiveWards:z.array(wardSchema),rngSeed:z.string(),eventSettings:eventSettingsSchema,victorySettings:victorySettingsSchema,victoryTargetSC:z.number().int().positive(),finalResult:endResultSchema.nullable(),timeline:z.array(logRecordSchema)}).strict();
export type MatchLog=z.infer<typeof matchLogSchema>;
export type LogRecord=z.infer<typeof logRecordSchema>;
