import { describe,it,expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { configSchema,datasetSchema,createConfig,WARDS,type RegionDataset } from '../shared/model';
import { matchLogSchema } from '../shared/match';
import { compileScenario,validateScenarioForOnlinePlay } from './scenario';
import { RoomManager,serializePublicState } from './room-manager';
import { defaultGameSettings,createOnlineBoard } from './initial';
import { sampleConfig,sampleDataset } from '../map-core/sample';
import { completeSyntheticScenario } from '../../tests/scenario-fixture';
import { compileMap } from '../map-core/compile';
import { createPreview } from '../shared/preview';
import { createGameSession,advanceGame,adjudicateGameOrders,adjudicateGameRetreats,adjudicateGameWinter,finalStandings,noEvents,type GameResponse } from '../game-core';
import { startMatchLog,logTransition,summarizeMatch,exportMatchLog } from '../game-core/match-log';
import type { OnlineResponse } from '../shared/online';

const ok=<T>(r:GameResponse<T>)=>{if(!r.ok)throw new Error(r.errors.join(';'));return r.result;};
const success=(r:OnlineResponse)=>{if(!r.ok)throw new Error(r.errors.join(';'));return r;};
function fixture(){const config=structuredClone(sampleConfig);config.regions['sample-a']={enabled:true,isSupplyCenter:true,homeWardId:'26101',startingUnit:{type:'army',ownerWardId:'26101'}};return completeSyntheticScenario(sampleDataset,config);}
function roomSetup(){const f=fixture();let clock='2026-10-03T00:00:00.000Z';const manager=new RoomManager({sample:f.dataset,'kyoto-kml':f.dataset},undefined,{settings:noEvents,seedFactory:()=> 'phase4b-test',now:()=>clock});const credentials=success(manager.request('s0',{action:'create',nickname:'host',preferredWardId:'26101',datasetKind:'sample',config:f.config})).credentials!;for(let i=1;i<3;i++)success(manager.request(`s${i}`,{action:'join',nickname:`guest${i}`,preferredWardId:WARDS[i].id,roomCode:credentials.roomCode}));const room=manager.rooms.get(credentials.roomCode)!;return {manager,room,f,credentials,time:(value:string)=>{clock=value;},start:()=>success(manager.request('s0',{action:'start',yearLimit:null})),submit:(i:number,finalize=true)=>manager.request(`s${i}`,{action:'orders',phaseKey:manager.phaseKey(room)!,orders:[],finalize})};}
function endFixture(counts:number[]) {
  const dataset:RegionDataset={version:1,kind:'sample',regions:[]};
  for(const [i,count] of counts.entries())for(let j=0;j<count+1;j++){const r=structuredClone(sampleDataset.regions[0]);r.regionId=`end-${i}-${j}`;r.name=r.regionId;r.wardId=WARDS[i].id;r.sourceAreaNumber=String(j+1);dataset.regions.push(r);}
  const config=createConfig(dataset);
  for(const [i,count] of counts.entries())for(let j=0;j<count+1;j++)config.regions[`end-${i}-${j}`]={enabled:true,isSupplyCenter:j<count,homeWardId:WARDS[i].id,startingUnit:j===0?{ownerWardId:WARDS[i].id,type:'army'}:null};
  const map=compileMap(dataset,config).map,state=ok(createGameSession(map,createPreview(map),WARDS.slice(0,counts.length).map(w=>w.id),null,15,{settings:noEvents,requiredRivalInitialSupplyCentersForInstantWin:0}));return {map,state};
}
describe('Phase 4B シナリオ',()=>{
  it('保存MapConfigのサーバーcompileと順序に依存しない元データ込みhash',()=>{const f=fixture(),a=compileScenario(f.dataset,JSON.stringify(f.config));const b=compileScenario(f.dataset,{...f.config,regions:Object.fromEntries(Object.entries(f.config.regions).reverse())});expect(a.hash).toBe(b.hash);expect(a.map.mapId).toBe(f.config.mapId);expect(a.loaded).toBe(true);});
  it.each(['{','{"version":999}',JSON.stringify({...sampleConfig,secret:true})])('不正JSON / MapConfigを拒否: %s',json=>expect(()=>compileScenario(sampleDataset,json)).toThrow());
  it('京都227原典と保存したテスト専用MapConfigをcompileする',()=>{const dataset=datasetSchema.parse(JSON.parse(readFileSync('data/generated/regions.json','utf8'))),config=configSchema.parse(JSON.parse(readFileSync('tests/fixtures/phase4b-kyoto-map-config.json','utf8')));const s=compileScenario(dataset,config),p=validateScenarioForOnlinePlay(s.map,s.config,3,undefined,s.report);expect(s.map.regions).toHaveLength(227);expect(p.errors).toEqual([]);expect(p.totalSC).toBe(33);expect(p.totalStartingUnits).toBe(11);});
  it('3人でも全11区の地域・軍・初期所有SCを要求',()=>{const f=fixture();for(const r of f.dataset.regions.filter(r=>r.wardId==='26109'))f.config.regions[r.regionId]={...f.config.regions[r.regionId],enabled:false,startingUnit:null};const s=compileScenario(f.dataset,f.config),p=validateScenarioForOnlinePlay(s.map,s.config,3);expect(p.errors.join(';')).toContain('伏見区');expect(p.errors.filter(e=>e.includes('伏見区'))).toHaveLength(3);});
  it('軍のdisabled・侵入不能・非SC、重複と不正隣接を拒否',()=>{const f=fixture(),s=compileScenario(f.dataset,f.config);s.map.regions[0].enabled=false;s.map.regions[0].playableGeometry=null;s.map.regions[0].isSupplyCenter=false;s.map.regions.push(structuredClone(s.map.regions[0]));s.map.adjacency['sample-b']=['missing'];expect(validateScenarioForOnlinePlay(s.map,s.config,3).errors.length).toBeGreaterThan(4);});
  it('人数別目標がSC総数を超えるなら開始不可',()=>{const f=fixture();for(const [id,s] of Object.entries(f.config.regions))if(id.startsWith('extra-sc-'))s.isSupplyCenter=false;const s=compileScenario(f.dataset,f.config);expect(validateScenarioForOnlinePlay(s.map,s.config,3).errors.join(';')).toContain('勝利目標23SC');});
  it('差・孤立などwarningだけなら開始し、maxYearsをsnapshot',()=>{const r=roomSetup();expect(r.manager.preflight(r.room).warnings.length).toBeGreaterThan(0);expect(r.manager.startErrors(r.room)).toEqual([]);r.start();expect(r.room.game!.state.maxYears).toBe(5);expect(r.room.game!.matchLog.victorySettings.maxYears).toBe(5);});
  it('Host限定読込、失敗時の旧シナリオ保持、開始後変更禁止',()=>{const r=roomSetup(),old=r.room.scenario.hash;expect(r.manager.request('s1',{action:'scenario',json:JSON.stringify(r.f.config)}).ok).toBe(false);expect(r.manager.request('s0',{action:'scenario',json:'{'}).ok).toBe(false);expect(r.room.scenario.hash).toBe(old);const config={...r.f.config,mapId:'loaded-test'};success(r.manager.request('s0',{action:'scenario',json:JSON.stringify(config)}));expect(r.room.scenario.loaded).toBe(true);expect(r.room.scenario.hash).not.toBe(old);r.start();expect(r.manager.request('s0',{action:'scenario',json:JSON.stringify(config)}).ok).toBe(false);});
});
describe('Phase 4B 共通終了判定',()=>{
  it.each(['spring','autumn'] as const)('%s SC更新で目標到達・最多の達成者だけが勝利',season=>{const {map,state}=endFixture([16,15,14]);state.phase='sc-update';state.season=season;const next=ok(advanceGame(map,state));expect(next.status).toBe('finished');expect(next.endResult).toMatchObject({reason:'supply-target',season,winners:['26101']});});
  it('同時達成の最高SC同数は同率勝者・同順位',()=>{const {map,state}=endFixture([16,16,14]);state.phase='sc-update';const next=ok(advanceGame(map,state));expect(next.endResult!.winners).toEqual(['26101','26102']);expect(next.endResult!.standings.map(r=>r.rank)).toEqual([1,1,3]);});
  it('12,12,10はSCだけで1,1,3（地域数・軍数で分けない）',()=>{const {map,state}=endFixture([12,12,10]);state.board.units=state.board.units.filter(u=>u.ownerWardId!=='26102');expect(finalStandings(map,state).map(r=>r.rank)).toEqual([1,1,3]);});
  it('冬の新規脱落でその冬に終わり、最多SCが勝利（規定年数より優先）',()=>{const {map,state}=endFixture([3,2,1]);state.phase='end-of-year';state.season='winter';state.year=5;state.board.regionControl['end-2-1'].controllerWardId=null;const next=ok(advanceGame(map,state));expect(next.endResult).toMatchObject({reason:'elimination-final-year',year:5,season:'winter',winners:['26101']});});
  it('既定5年を全季節進め、第5年冬清算後だけ終了',()=>{const {map,state}=endFixture([2,2,2]);let current=state;for(let year=1;year<=5;year++){for(let season=0;season<2;season++){expect(current.status).toBe('playing');current=ok(adjudicateGameOrders(map,current,current.board.units.map(u=>({type:'hold',unitId:u.unitId}))));current=ok(adjudicateGameRetreats(map,current,[]));current=ok(advanceGame(map,current));current=ok(advanceGame(map,current));}expect(current.phase).toBe('adjustments');current=ok(adjudicateGameWinter(map,current,{builds:[],disbands:[]}));expect(current.status).toBe('playing');current=ok(advanceGame(map,current));expect(current.status).toBe(year===5?'finished':'playing');}expect(current.endResult).toMatchObject({reason:'max-years',year:5,winners:['26101','26102','26103']});});
  it('終了後はcoreの命令・撤退・冬・次へ全て拒否する',()=>{const {map,state}=endFixture([16,2,2]);state.phase='sc-update';const end=ok(advanceGame(map,state));for(const r of [adjudicateGameOrders(map,end,[]),adjudicateGameRetreats(map,end,[]),adjudicateGameWinter(map,end,{builds:[],disbands:[]}),advanceGame(map,end)])expect(r.ok).toBe(false);});
});
describe('Phase 4B telemetry・公開・export',()=>{
  it('実裁定のバリケード使用・設置・4季後の期限終了をログへ一度ずつ保存',()=>{
    const {map,state}=endFixture([2,2,2]);
    map.adjacency['end-0-0']=['end-0-1','end-0-2'];map.adjacency['end-0-1']=['end-0-0','end-0-2'];map.adjacency['end-0-2']=['end-0-0','end-0-1'];
    state.events.inventory=[{equipmentId:'wall-test',type:'barricade',ownerWardId:'26101'}];
    let log=startMatchLog({gameId:'wall-lifecycle',scenarioHash:'test',playerCount:3,wardAssignment:{},players:[],inactiveWards:[],rngSeed:state.events.seed,eventSettings:state.events.settings,victorySettings:defaultGameSettings,victoryTargetSC:15},map,state,'2026-10-03T00:00:00.000Z');
    let current=state,seconds=0;
    function apply(response:GameResponse,orders:Parameters<typeof adjudicateGameOrders>[2]=[]){const next=ok(response);log=logTransition(log,map,current,next,new Date(Date.UTC(2026,9,3,0,0,++seconds)).toISOString(),orders);current=next;}
    const deployment=current.board.units.map(u=>u.ownerWardId==='26101'?{type:'deploy-barricade' as const,unitId:u.unitId,targetRegionId:'end-0-1',equipmentId:'wall-test'}:{type:'hold' as const,unitId:u.unitId});
    apply(adjudicateGameOrders(map,current,deployment),deployment);
    function finishSeason(){apply(adjudicateGameRetreats(map,current,[]));apply(advanceGame(map,current));apply(advanceGame(map,current));if(current.phase==='adjustments'){apply(adjudicateGameWinter(map,current,{builds:[],disbands:[]}));apply(advanceGame(map,current));}}
    finishSeason();
    for(let i=0;i<4;i++){const orders=current.board.units.map(u=>({type:'hold' as const,unitId:u.unitId}));apply(adjudicateGameOrders(map,current,orders),orders);finishSeason();}
    expect(log.timeline.filter(r=>r.type==='barricade-expiration')).toHaveLength(1);expect(summarizeMatch(log)).toMatchObject({barricadeUses:1,barricadeDeployments:1});expect(current.events.activeBarricades).toEqual([]);expect(matchLogSchema.safeParse(log).success).toBe(true);
  });
  it('裁定前は命令なし、確定時間・全員時間・裁定後命令を記録',()=>{const r=roomSetup();r.start();r.time('2026-10-03T00:00:10.000Z');success(r.submit(0));let log=success(r.manager.request('s0',{action:'export-log'})).matchLog!;expect(log.timeline.some(e=>e.resolvedOrders)).toBe(false);expect(log.timeline.find(e=>e.type==='player-finalized')!.elapsedSeconds).toBe(10);r.time('2026-10-03T00:00:20.000Z');success(r.submit(1));r.time('2026-10-03T00:00:30.000Z');success(r.submit(2));log=success(r.manager.request('s0',{action:'export-log'})).matchLog!;expect(log.timeline.find(e=>e.type==='adjudication')).toMatchObject({elapsedSeconds:30,submittedOrderCount:3});expect(summarizeMatch(log).averageOrdersSeconds).toBe(30);expect(log.timeline.find(e=>e.type==='sc-update')).toMatchObject({season:'spring',phase:'sc-update'});expect(matchLogSchema.safeParse(log).success).toBe(true);expect(JSON.stringify(log)).not.toContain(r.credentials.reconnectToken);expect(JSON.stringify(log)).not.toContain('socketId');expect(JSON.stringify(log)).not.toContain('reservations');});
  it('進行中はHostのみ、終了後は全員export・同じ結果・再接続、提出全種拒否',()=>{const r=roomSetup();r.start();expect(r.manager.request('s1',{action:'export-log'}).ok).toBe(false);const game=r.room.game!;game.state.phase='end-of-year';game.state.season='winter';game.state.year=5;game.state=ok(advanceGame(r.room.map,game.state));game.matchLog=logTransition(game.matchLog,r.room.map,{...game.state,status:'playing',phase:'end-of-year'},game.state,'2026-10-03T00:01:00.000Z');for(let i=0;i<3;i++){const log=success(r.manager.request(`s${i}`,{action:'export-log'})).matchLog!;expect(log.finalResult).toEqual(game.state.endResult);expect(serializePublicState(r.manager,r.room).game!.endResult).toEqual(log.finalResult);for(const request of [{action:'orders',orders:[]},{action:'retreats',orders:[]},{action:'winter',draft:{buildRegionIds:[],disbandUnitIds:[]}}])expect(r.manager.request(`s${i}`,{...request,phaseKey:r.manager.phaseKey(r.room),finalize:true}).ok).toBe(false);}r.manager.disconnect('s0');expect(r.manager.request('restored',{action:'reconnect',...r.credentials}).ok).toBe(true);});
  it('同じ時刻・入力ならログは決定的で、生成・pickup・設置・期限を客観集計',()=>{const {map,state}=endFixture([2,2,2]);state.events.current=[{type:'bicycle',regionId:'end-0-2'}];state.events.groundEquipment=[{equipmentId:'test-bike',type:'bicycle',regionId:'end-0-2',spawnedYear:1,spawnedSeason:'spring'}];const metadata={gameId:'deterministic-test',scenarioHash:'test-only',playerCount:3,wardAssignment:{p0:'26101' as const,p1:'26102' as const,p2:'26103' as const},players:[],inactiveWards:[],rngSeed:'same',eventSettings:state.events.settings,victorySettings:defaultGameSettings,victoryTargetSC:15};const initial=startMatchLog(metadata,map,state,'2026-10-03T00:00:00.000Z');const moved=ok(adjudicateGameOrders(map,state,state.board.units.map(u=>({type:'hold',unitId:u.unitId}))));const pickupUnits=moved.board.units.map((u,i)=>i===0?{...u,regionId:'end-0-2'}:u);const before={...moved,board:{...moved.board,units:pickupUnits},movement:{...moved.movement!,units:pickupUnits}};const after=ok(adjudicateGameRetreats(map,before,[]));const a=logTransition(initial,map,before,after,'2026-10-03T00:01:00.000Z');expect(a).toEqual(logTransition(initial,map,before,after,'2026-10-03T00:01:00.000Z'));expect(summarizeMatch(a)).toMatchObject({bicyclePickups:1,eventCounts:{bicycle:1}});expect(exportMatchLog(a)).toEqual(a);expect(createOnlineBoard(map,['26101']).units).toHaveLength(1);});
});
